blank_issues_enabled: false
contact_links:
  - name: If you have a feature request or idea.
    url: https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/ideas
    about: Show your feature request or idea to our community.
  - name: I have a question or need support, Ask the community for help
    url: https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/support
    about: Let the people of our community help you.
  - name: Offical Windcentrale website
    url: https://www.windcentrale.nl/
    about: For people who want to know more about the windturbines; I'm not related to this company.